- hosts: 18.191.146.198
  become: true
  tasks: 
    - name: Installing apache on web01
      apt: 
       name: apache2 
       update_cache: yes 
       state: latest
    - name: Modifying html folder and index archive
      copy:
        src: ./web01/index.html
        dest: /var/www/html/index.html
        force: yes
- hosts: 3.15.216.5
  become: true
  tasks:
    - name: Installing apache on web02
      apt:
       name: apache2
       update_cache: yes
       state: latest
    - name: Modifying html folder and index archive
      copy:
        src: ./web02/index.html
        dest: /var/www/html/index.html
        force: yes
- hosts: 13.59.251.115
  become: true
  tasks:
    - name: Installing HAProxy
      apt: 
       name: haproxy
       update_cache: yes
       state: latest
    - name: Configuring the HAProxy.
      shell: echo "ENABLED=1" >> /etc/default/haproxy
    - name: Configuring the HAProxy..
      shell: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
    - name: Configuring the HAProxy...
      template:
         src: ./haproxy.cfg
         dest: /etc/haproxy/haproxy.cfg
         mode: 0644
    - name: Initializing HAProxy
      systemd:
         name: haproxy
         enabled: yes
         state: started
    - name: Restating HAProxy
      systemd:
         name: haproxy
         enabled: yes
         state: restarted
